# Generated by Django 4.2.28 on 2026-02-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(default='USA', max_length=80)),
            ],
        ),
    ]
