# Generated by Django 4.2.28 on 2026-02-23 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_routes', to='flights.airport')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_routes', to='flights.airport')),
            ],
        ),
    ]
