# Generated by Django 4.2.28 on 2026-02-23 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='iata_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='route',
            name='from_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='flights.airport'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_at', models.DateTimeField()),
                ('arrive_at', models.DateTimeField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.route'),
        ),
    ]
